const images = [
    {
      title: "Bibliotèque salon",
      src: require("@/assets/img/biblio/biblio.jpg"),
      thumbnail:  require("@/assets/thumbs/biblio/biblio.jpg"),
      w: 900, 
      h: 900,
      alt: 'Bibliotèque salon', 
    },
    {
      title: "Bibliotèque chambre",
      src: require("@/assets/img/biblio/vergne.jpg"),
      thumbnail: require("@/assets/thumbs/biblio/vergne.jpg"),
      w: 900, 
      h: 900,
      alt: 'Bibliotèque chambre', 
    },
    {
        title: "Dressing",
        src: require("@/assets/img/dressing/img.jpg"),
        thumbnail: require("@/assets/thumbs/dressing/img.jpg"),
        w: 900, 
        h: 900,
        alt: 'Dressing',
      },
    {
      title: "Grande bibliotèque de salon",
      src: require("@/assets/img/biblio/ArSalon.jpg"),
      thumbnail: require("@/assets/thumbs/biblio/ArSalon.jpg"),
      w: 900, 
      h: 900,
      alt: 'Grande bibliotèque de salon',
    },
    {
      title: "Bibliotèque salon",
      src: require("@/assets/img/biblio/DSC0045.jpg"),
      thumbnail: require("@/assets/thumbs/biblio/DSC0045.jpg"),
      w: 900, 
      h: 900,
      alt: 'Bibliotèque salon',
    },
    {
      title: "Bibliotèque salon",
      src: require("@/assets/img/biblio/biblioSAlon.jpg"),
      thumbnail: require("@/assets/thumbs/biblio/biblioSAlon.jpg"),
      w: 900, 
      h: 900,
      alt: 'Bibliotèque salon',
    },
    {
      title: "Dressing",
      src: require("@/assets/img/dressing/dressing.jpg"),
      thumbnail: require("@/assets/thumbs/dressing/dressing.jpg"),
      w: 900, 
      h: 900,
      alt: 'Dressing',
    },
    {
      title: "Dressing",
      src: require("@/assets/img/dressing/lightFirst.jpg"),
      thumbnail: require("@/assets/thumbs/dressing/lightFirst.jpg"),
      w: 900, 
      h: 900,
      alt: 'Dressing',
    },
    {
      title: "Dressing",
      src: require("@/assets/img/dressing/light.jpg"),
      thumbnail: require("@/assets/thumbs/dressing/light.jpg"),
      w: 900, 
      h: 900,
      alt: 'Dressing',
    },
    {
      title: "Dressing",
      src: require("@/assets/img/dressing/miniDress.jpg"),
      thumbnail: require("@/assets/thumbs/dressing/miniDress.jpg"),
      w: 900, 
      h: 900,
      alt: 'Dressing',
    },
    {
        title: "Dressing",
        src: require("@/assets/img/dressing/autreDress.jpg"),
        thumbnail: require("@/assets/thumbs/dressing/autreDress.jpg"),
        w: 900, 
        h: 900,
        alt: 'Dressing',
      },
    {
      title: "Dressing",
      src: require("@/assets/img/dressing/mini.jpeg"),
      thumbnail: require("@/assets/thumbs/dressing/mini.jpg"),
      w: 900, 
      h: 900,
      alt: 'Dressing',
    },
    {
        title: "Dressing",
        src: require("@/assets/img/dressing/miniPortes.jpg"),
        thumbnail: require("@/assets/thumbs/dressing/miniPortes.jpg"),
        w: 900, 
        h: 900,
        alt: 'Dressing',
      },
    {
      title: "Dressing",
      src: require("@/assets/img/dressing/sorin.jpeg"),
      thumbnail: require("@/assets/thumbs/dressing/sorin.jpg"),
      w: 900, 
      h: 900,
      alt: 'Dressing',
    },
    {
        title: "Dressing",
        src: require("@/assets/img/dressing/whiteDress.jpg"),
        thumbnail: require("@/assets/thumbs/dressing/whiteDress.jpg"),
        w: 900, 
        h: 900,
        alt: 'Dressing',
      },
    // {
    //   title: "Placard portes ouvertes",
    //   src: require("@/assets/img/placard/placard1.jpg"),
    //   thumbnail: require("@/assets/thumbs/placard/placard1.jpg"),
    //   w: 900, 
    //   h: 900,
    //   alt: 'Placard',
    // },
    // {
    //   title: "Placard portes fermé",
    //   src: require("@/assets/img/placard/placard2.jpg"),
    //   thumbnail: require("@/assets/thumbs/placard/placard2.jpg"),
    //   w: 900, 
    //   h: 900,
    //   alt: 'Placard',
    // },
    {
        title: "Placard d'entrée",
        src: require("@/assets/img/placard/placard42.jpg"),
        thumbnail: require("@/assets/thumbs/placard/placard42.jpg"),
        w: 900, 
        h: 900,
        alt: 'Placard',
      },
    {
      title: "Placard d'entrée",
      src: require("@/assets/img/placard/placard4.jpg"),
      thumbnail: require("@/assets/thumbs/placard/placard4.jpg"),
      w: 900, 
      h: 900,
      alt: 'Placard',
    },
    // {
    //   title: "Placard a chaussures",
    //   src: require("@/assets/img/placard/placard5.jpg"),
    //   thumbnail: require("@/assets/thumbs/placard/placard5.jpg"),
    //   w: 900, 
    //   h: 900,
    //   alt: 'Placard',
    // },
    // {
    //   title: "Placard a chaussures",
    //   src: require("@/assets/img/placard/placard6.jpg"),
    //   thumbnail: require("@/assets/thumbs/placard/placard6.jpg"),
    //   w: 900, 
    //   h: 900,
    //   alt: 'Placard',
    // },
    {
      title: "Tv mirroir et etagères",
      src: require("@/assets/img/placard/etagers.jpeg"),
      thumbnail: require("@/assets/thumbs/placard/etagers.jpg"),
      w: 900, 
      h: 900,
      alt: 'Placard',
    },
    {
      title: "Bibliotèque sous l'escalier",
      src: require("@/assets/img/placard/placard8.jpg"),
      thumbnail: require("@/assets/thumbs/placard/placard8.jpg"),
      w: 900, 
      h: 900,
      alt: 'Placard',
    },
    {
      title: "Petites meubles de buanderie",
      src: require("@/assets/img/placard/placard10.jpg"),
      thumbnail: require("@/assets/thumbs/placard/placard10.jpg"),
      w: 900, 
      h: 900,
      alt: 'Placard',
    },
    {
      title: "Petites meuble toilette",
      src: require("@/assets/img/placard/placard11.jpg"),
      thumbnail: require("@/assets/thumbs/placard/placard11.jpg"),
      w: 900, 
      h: 900,
      alt: 'Placard',
    },
    {
      title: "Meuble cache boitier et tuyaux",
      src: require("@/assets/img/placard/placard12.jpg"),
      thumbnail: require("@/assets/thumbs/placard/placard12.jpg"),
      w: 900, 
      h: 900,
      alt: 'Placard',
    },
    {
      title: "Cuisine",
      src: require("@/assets/img/cuisine/cuisineVertGauche.jpg"),
      thumbnail: require("@/assets/thumbs//cuisine/cuisineVertGauche.jpg"),
      w: 900, 
      h: 900,
      alt: 'Cuisine',
    },
    {
      title: "Cuisine",
      src: require("@/assets/img/cuisine/cuisineVertDroit.jpg"),
      thumbnail: require("@/assets/thumbs//cuisine/cuisineVertDroit.jpg"),
      w: 900, 
      h: 900,
      alt: 'Cuisine',
    },
    {
      title: "Cuisine",
      src: require("@/assets/img/cuisine/cusineGri.jpg"),
      thumbnail: require("@/assets/thumbs//cuisine/cusineGri.jpg"),
      w: 900, 
      h: 900,
      alt: 'Cuisine',
    },
    {
      title: "Cuisine",
      src: require("@/assets/img/cuisine/cuisineAlexPD.jpg"),
      thumbnail: require("@/assets/thumbs//cuisine/cuisineAlexPD.jpg"),
      w: 900, 
      h: 900,
      alt: 'Cuisine',
    },
    {
      title: "Cuisine",
      src: require("@/assets/img/cuisine/orgeval.jpg"),
      thumbnail: require("@/assets/thumbs//cuisine/orgeval.jpg"),
      w: 900, 
      h: 900,
      alt: 'Cuisine',
    },
    {
      title: "Cuisine",
      src: require("@/assets/img/cuisine/blanche.jpg"),
      thumbnail: require("@/assets/thumbs/cuisine/blanche.jpg"),
      w: 900, 
      h: 900,
      alt: 'Cuisine',
    },
    {
      title: "Pose parquet",
      src: require("@/assets/img/parquet/img.jpg"),
      thumbnail: require("@/assets/thumbs/parquet/img.jpg"),
      w: 900, 
      h: 900,
      alt: 'Pose parquet',
    },
    {
      title: "Pose parquet",
      src: require("@/assets/img/parquet/parquetHall.jpg"),
      thumbnail: require("@/assets/thumbs/parquet/parquetHall.jpg"),
      w: 900, 
      h: 900,
      alt: 'Pose parquet',
    },
    // {
    //   title: "Pose parquet",
    //   src: require("@/assets/img/parquet/beauParquet.jpeg"),
    //   thumbnail: require("@/assets/thumbs/parquet/beauParquet.jpeg"),
    //   w: 900, 
    //   h: 900,
    //   alt: 'Pose parquet',
    // },
    {
      title: "Escaliers",
      src: require("@/assets/img/stairs/stair.jpg"),
      thumbnail: require("@/assets/thumbs/stairs/stair.jpg"),
      w: 900, 
      h: 900,
      alt: 'Escaliers',
    },
    {
      title: "Escaliers",
      src: require("@/assets/img/stairs/colimacon.jpg"),
      thumbnail: require("@/assets/thumbs/stairs/colimacon.jpg"),
      w: 900, 
      h: 900,
      alt: 'Escaliers',
    },
    {
      title: "Escaliers",
      src: require("@/assets/img/stairs/Paris.jpg"),
      thumbnail: require("@/assets/thumbs/stairs/Paris.jpg"),
      w: 900, 
      h: 900,
      alt: 'Escaliers',
    },
    {
      title: "Escaliers",
      src: require("@/assets/img/stairs/Stairs.jpg"),
      thumbnail: require("@/assets/thumbs/stairs/Stairs.jpg"),
      w: 900, 
      h: 900,
      alt: 'Escaliers',
    },
    {
      title: "Escaliers",
      src: require("@/assets/img/stairs/Champigny.jpg"),
      thumbnail: require("@/assets/thumbs/stairs/Champigny.jpg"),
      w: 900, 
      h: 900,
      alt: 'Escaliers',
    },
    {
      title: "Meubles salle de bain",
      src: require("@/assets/img/sdb/Bain.jpg"),
      thumbnail: require("@/assets/thumbs/sdb/Bain.jpg"),
      w: 900, 
      h: 900,
      alt: 'Meubles salle de bain',
    },
    {
      title: "Meuble salle de bain",
      src: require("@/assets/img/sdb/SalleBain.jpg"),
      thumbnail: require("@/assets/thumbs/sdb/SalleBain.jpg"),
      w: 900, 
      h: 900,
      alt: 'Meubles salle de bain',
    },
    // {
    //   title: "Meuble toilette",
    //   src: require("@/assets/img/sdb/toilette.jpeg"),
    //   thumbnail: require("@/assets/thumbs/sdb/toilette.jpeg"),
    //   w: 900, 
    //   h: 900,
    //   alt: 'Meubles salle de bain',
    // },
    {
      title: "Meuble salle de bain",
      src: require("@/assets/img/sdb/IMG20171211.jpg"),
      thumbnail: require("@/assets/thumbs/sdb/IMG20171211.jpg"),
      w: 900, 
      h: 900,
      alt: 'Meubles salle de bain',
    },
    {
      title: "Meuble salle de bain",
      src: require("@/assets/img/sdb/DSC0119.jpg"),
      thumbnail: require("@/assets/thumbs/sdb/DSC0119.jpg"),
      w: 900, 
      h: 900,
      alt: 'Meubles salle de bain',
    },
    {
      title: "Meuble salle de bain",
      src: require("@/assets/img/sdb/sdb.jpg"),
      thumbnail: require("@/assets/thumbs/sdb/sdb.jpg"),
      w: 900, 
      h: 900,
      alt: 'Meubles salle de bain',
    },
    // {
    //   title: "Pose porte",
    //   src: require("@/assets/img/porte/DSC_0045(2).jpg"),
    //   thumbnail: require("@/assets/thumbs/porte/DSC_0045(2).jpg"),
    //   w: 900, 
    //   h: 900,
    //   alt: 'Pose porte',
    // },
    {
      title: "Pose porte",
      src: require("@/assets/img/porte/portecoulissante.jpg"),
      thumbnail: require("@/assets/thumbs/porte/portecoulissante.jpg"),
      w: 900, 
      h: 900,
      alt: 'Pose porte',
    },
    {
      title: "Pose porte",
      src: require("@/assets/img/porte/porte-coulissante2.jpg"),
      thumbnail: require("@/assets/thumbs/porte/porte-coulissante2.jpg"),
      w: 900, 
      h: 900,
      alt: 'Pose porte',
    },
  ];
  export default images;
  